print("How many years old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()
print("In which units is your answer for weight (kg, lbs, stone, etc.,)?")
unit_of_weight = input()

print(f"So, you're {age} years old, {height} tall, and {weight} {unit_of_weight} heavy.")
